name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [BakeryManagement, BusBooking, ElectricBillCalculator, EmployeeData, RunningCalCount]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and Test ${{ matrix.project }}
      run: |
        cd ${{ matrix.project }}
        ./gradlew build # or ./mvnw clean install if using Maven

    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.project }}-artifacts
        path: ${{ matrix.project }}/build # or ${{ matrix.project }}/target if using Maven
